### ISSUE TITLE
Will vulkan's hooking be simpler than dx12? Little is known about vulkan

### ISSUE THREAD

**Issue by scx1125** [Sh0ckFR/Universal-Dear-ImGui-Hook#1]
Will vulkan's hooking be simpler than dx12? Little is known about vulkan

**Comment by Sh0ckFR** [comment]
I never used Vulkan yet so I don't really know, but according to some friends, it's more easier

**Comment by scx1125** [comment]
thx,Support this project, hope to make an example about vulkan

**Comment by Sh0ckFR** [comment]
Yes I will try later, I don't have too much free time actually, so I can't for the moment.

Ps : If someone read this and did it already, don't hesitate to do a pull request for the community ;)
