### ISSUE TITLE
Error C1047 when building

### ISSUE THREAD

**Issue by Literally-CJ** [Sh0ckFR/Universal-Dear-ImGui-Hook#11]
When building, I get error C1047 as seen below:
![image](https://user-images.githubusercontent.com/86020934/122279361-dca8a200-cedf-11eb-9157-cf336fe07774.png)

Unlike in #2 , when cloning from GitHub Desktop, I still get the error and cannot build.

**Comment by mnemonic-re** [comment]
Go to: https://github.com/TsudaKageyu/minhook and clone the repository. Go in this folder if you are using Visual Studio 2019: \minhook-master\build\VC16

Open the solution, set it to Release x64 and build. You will find libMinHook.x64.lib in: \minhook-masterbuild\VC16\lib\Release.

Copy libMinHook.x64.lib to Universal-Dear-ImGui-Hook-master\minhook\lib and overwrite the existing lib file. Now compile the solution.

**Comment by Literally-CJ** [comment]
> Go to: https://github.com/TsudaKageyu/minhook and clone the repository. Go in this folder if you are using Visual Studio 2019: \minhook-master\build\VC16
> 
> Open the solution, set it to Release x64 and build. You will find libMinHook.x64.lib in: \minhook-master\build\VC16\lib\Release.
> 
> Copy libMinHook.x64.lib to Universal-Dear-ImGui-Hook-master\minhook\lib and overwrite the existing lib file. Now clean and recompile the solution. It will compile the dll.

Thank you! This has solved my problem! 👍
