### ISSUE TITLE
Nothing Shows Upon Injection

### ISSUE THREAD

**Issue by 0xDani3l** [Sh0ckFR/Universal-Dear-ImGui-Hook#14]
Hi there. I compiled the project as x64 Release, then injected it into an x64 D3D11 process with cheat engine. (Also tried GH injector)

Upon injecting, I get a success message, though nothing changes. When clicking insert, nothing shows up.

Any ideas? Same thing happens when using this hook too - https://github.com/guided-hacking/GH_D3D11_Hook

**Comment by Sh0ckFR** [comment]
Hello,

This project is actually working only on D3D12 (I specified it in the description), if you want to work on D3D11, you need to use my old project here: https://github.com/Sh0ckFR/Universal-ImGui-D3D11-Hook

Have a good day

**Comment by 0xDani3l** [comment]
Gotcha, thank you. When compiling that version, I get "LNK118 cannot open input file 'libMinHook-x64-v140-mdd.lib"

I compiled the latest github Minhook lib for Vs 2019, but I'm not sure how to point the project to the new lib file. Also not sure if it's a different lib, as the new one doesn't have the "-mdd" in it.

Thanks for the help =)

**Comment by Sh0ckFR** [comment]
Hello,

https://stackoverflow.com/a/4446085 Here is the solution to import a library, you can import the new version of minhook it is not a problem
