### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by websecnl** [Sh0ckFR/Universal-Dear-ImGui-Hook#15]
What compiler version was used to compile this code?

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1047	The object or library file 'C:\Users\Eigenaar\Desktop\Universal-Dear-ImGui-Hook-master\minhook\lib\libMinHook.x64.lib' was created by a different version of the compiler than other objects like 'x64\Release\d3d12hook.obj'; rebuild all objects and libraries with the same compiler	Halo-Hook	C:\Users\Eigenaar\Desktop\Universal-Dear-ImGui-Hook-master\LINK	1

**Comment by Sh0ckFR** [comment]
hello, I don't remember but here is the solution: https://github.com/Sh0ckFR/Universal-Dear-ImGui-Hook#getting-started

```
If you have an error about libMinHook.x64.lib, recompile https://github.com/TsudaKageyu/minhook in x64 and replace the old .lib file by your new one.
````
