### ISSUE TITLE
Direct X Error

### ISSUE THREAD

**Issue by hazbot77** [Sh0ckFR/Universal-Dear-ImGui-Hook#18]
I am getting the error "directx has encountered an unrecoverable error" when injecting this into COD Warzone, any idea whats going on?

**Comment by Sh0ckFR** [comment]
It looks like a crash of the game itself, do you have any more informations?

**Comment by hazbot77** [comment]
Well it was injected using the method native inject, here is a screenshot of dllmain if that helps
![Screenshot 2021-11-27 104419](https://user-images.githubusercontent.com/74121606/143661400-6e8f65c4-10e4-4d66-9e8c-ad681b4d1fea.png)
:

**Comment by Sh0ckFR** [comment]
Okay and can you give me a screenshot of the result? when you injecting your dll please, or any useful informations like your crash logs or something?

Thank you
