### ISSUE TITLE
Cyberpunk freezes when menu is open

### ISSUE THREAD

**Issue by MelonHell** [Sh0ckFR/Universal-Dear-ImGui-Hook#19]
When you press insert, the menu opens and the game freezes, does not respond to any input. Hangs only when closing the menu through the debugger.

As I understand the problem in the method in inputhook.cpp

`	LRESULT APIENTRY WndProc(HWND hwnd, UINT uMsg, WPARAM wParam, LPARAM lParam)
	{
		if (menu::isOpen) {
			ImGui_ImplWin32_WndProcHandler(hwnd, uMsg, wParam, lParam);
			return true;
		}
		return CallWindowProc(oWndProc, hwnd, uMsg, wParam, lParam);
	}`

if you remove "return true;" then everything works, but the cursor is frozen in the center and continues to control the game

**Comment by Sh0ckFR** [comment]
It's a normal behavior, you need to adapt the code for your game (each game use the keyboard/mouse inputs differently)
