### ISSUE TITLE
Building minHook and this project with latest toolset and sdk causes "Invalid DisplaySize"

### ISSUE THREAD

**Issue by ghost** [Sh0ckFR/Universal-Dear-ImGui-Hook#6]
Solution and dependencies targeted for the following -
Windows SDK: 10.0 (latest)
Platform Toolset: Visual Studio 2019 (v142)
Language Standard: C++ 17

Error upon injection: "Assertion Failed: 'Invalid DisplaySize value!'

**Comment by 12brendon34** [comment]
it doesn't even build for me at all

**Comment by Sh0ckFR** [comment]
@glubdos I will take a look on it tonight, but you can use a debugger or the windows core dump files to debug it next time ;) have a good day
