### ISSUE TITLE
Wont build due to uresolved externals 

### ISSUE THREAD

**Issue by alemerus** [Sh0ckFR/Universal-Dear-ImGui-Hook#7]
![vs](https://user-images.githubusercontent.com/67514836/86529766-5a1b0400-be81-11ea-916f-f1e24a49e769.PNG)

**Comment by skyracer2012** [comment]
I have the same issue. Did you find anything? I think its because of double inclusion or something not sure tho

**Comment by skyracer2012** [comment]
I fond the issue. You have to recompile libMinHook.x64.lib from https://github.com/TsudaKageyu/minhook with help of https://github.com/TsudaKageyu/minhook/issues/62. Just change this platformset to v142 and you are all set.

**Comment by Sh0ckFR** [comment]
https://github.com/Sh0ckFR/Universal-ImGui-D3D11-Hook/issues/13 Yes, already specified it in the old project ;)
