### ISSUE TITLE
imgui doesnt show up

### ISSUE THREAD

**Issue by im-fin** [Sh0ckFR/Universal-Dear-ImGui-Hook#9]
when I inject it into a process it doesnt open or anything, is there a keybind needed?

**Comment by Samg381** [comment]
Same issue here.

**Comment by Sh0ckFR** [comment]
Hello,

You can find the different keys here : https://github.com/Sh0ckFR/Universal-Dear-ImGui-Hook/blob/master/globals.cpp

If you have any more issues, please provide me some debug informations :

Are you injecting in a D12 process ? 32 or 64 bits ?

Did you tested to attach a debugger to know what is happens ? if yes, can you provide me your logs ?

**Comment by thewolfram** [comment]
> Hello,
> 
> You can find the different keys here : https://github.com/Sh0ckFR/Universal-Dear-ImGui-Hook/blob/master/globals.cpp
> 
> If you have any more issues, please provide me some debug informations :
> 
> Are you injecting in a D12 process ? 32 or 64 bits ?
> 
> Did you tested to attach a debugger to know what is happens ? if yes, can you provide me your logs ?

I'm injecting to D11 x64 process. Tried defining D12 and D11 both and also changed FindWindow in dllmain.cpp but no success

**Comment by Sh0ckFR** [comment]
You need to inject in a D12 application only actually in x64, if you have any issues, don't hesitate a debugger to your application and share me the error messages please
